run_name: L_sample

# Map settings
pad_to: 24
min_grid_size: 17
max_grid_size: 23
mountain_density_min: 0.18
mountain_density_max: 0.26
castle_val_min: 40
castle_val_max: 51
num_cities_min: 8
num_cities_max: 13

# Pool
pool_size: 200000
reset_pool_every: 20

# Curriculum
curriculum:
  - min_generals_distance: 2
    max_generals_distance: 6
    reward_fn: win_lose_reward

  - win_rate_threshold: 0.6
    min_generals_distance: 4
    max_generals_distance: 8
    reward_fn: win_lose_reward

  - win_rate_threshold: 0.6
    min_generals_distance: 6
    max_generals_distance: 13
    reward_fn: win_lose_reward

  - win_rate_threshold: 0.6
    min_generals_distance: 11
    max_generals_distance: 17
    reward_fn: win_lose_reward

  - win_rate_threshold: 0.6
    min_generals_distance: 17
    max_generals_distance: 28
    reward_fn: win_lose_reward

  - win_rate_threshold: 0.6
    min_generals_distance: 17
    max_generals_distance: 42
    reward_fn: win_lose_reward

# Network
network: history_transformer
depth: 8
embed_dim: 448
n_head: 8
ff_factor: 3
patch_size: 3
conv_dim: 256
use_bf16: true

# Reward / opponent
reward_fn: win_lose_reward
initial_reward_fn: win_lose_reward
opponent: self
opponent_path: ''
init_checkpoint: ''
ema_checkpoint: ''
ema_decay: 0.999

# Rollout
num_envs: 512
num_steps: 512
truncation: 2048
num_iters: 2000
minibatch_size: 1024
seed: 44
num_epochs: 1

# PPO
gamma: 1.0
gamma_end: 1.0
gamma_anneal_iters: 0
gae_lambda: 0.9
clip_eps: 0.2
max_grad_norm: 0.267
vf_coef: 0.5
target_kl: 0.02
adv_top_frac: 0.25

# Entropy
ent_schedule: power_law
ent_coef_start: 0.05
ent_power: 0.2
ent_coef_min: 0.001
ent_coef_end: 0.001
ent_coef_decay_iters: 5000

# Learning rate
lr: 1e-4
warmup_lr: 0.0
lr_warmup_iters: 0
final_lr: 0.0
lr_decay_iters: 0
lr_schedule: power_law
lr_power_law_numerator: 0.5
lr_power_law_exponent: 1.17
lr_power_law_min: 5e-06
lr_power_law_max: 1e-4

# Eval
eval_every: 25
eval_every_after: 200
eval_games: 256
eval_ema_only: true
final_stage_rolling_eval: true
ckpt_every: 100
save_every: 200

# Checkpoints
ckpt_pool_size: 0

# Population training (disabled)
population_enabled: false
population_extend_every: 1000
population_max_size: 20
population_initial_paths:
best_cp_proportion: 0.75

# Value loss
value_loss: ce
num_bins: 128
v_min: -1.0
v_max: 1.0
hl_sigma: 0.04

magnet_policy: expander

debug: false
